export const Constance = {
    LOAD_ITEMS: 'LOAD_ITEMS',
    ADD_ITEM: 'ADD_ITEM',
    DONE_ITEM: 'DONE_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CHANGE_SEARCH: 'CHANGE_SEARCH',
    CHANGE_STATUS: 'CHANGE_STATUS',
    SYNC_ITEMS: 'SYNC_ITEMS',

    REQUEST: '_REQUEST',
    SUCCESS: '_SUCCESS',
    RESPONSE_FAIL: 'RESPONSE_FAIL'
};